### ISSUE TITLE
[BUG] Static fltk_gl library missing on macOS.

### ISSUE THREAD

**Issue by Ionizing** [fltk-rs/fltk-rs#881] opened 2021-09-11 17:23 UTC
## Describe the bug
```
$ cargo build  # With 'features=["fltk-bundled", "enable-glwindow"]'
error: could not find native static library `fltk_gl`, perhaps an -L flag is missing?

error: aborting due to previous error

error: could not compile `fltk-sys`

$ cargo build --verbose
   Compiling fltk-sys v1.1.17
     Running `rustc --crate-name fltk_sys --edition=2018 /Users/ionizing/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/fltk-sys-1.1.17/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="default"' --cfg 'feature="enable-glwindow"' --cfg 'feature="fltk-bundled"' -C metadata=2b3e1e4f037bb4c0 -C extra-filename=-2b3e1e4f037bb4c0 --out-dir /Users/ionizing/github/unitconv/target/debug/deps 
-L dependency=/Users/ionizing/github/unitconv/target/debug/deps --cap-lints allow 
-L native=/Users/ionizing/github/unitconv/target/debug/build/fltk-sys-c2de63b8459b5e6d/out/build 
-L native=/Users/ionizing/github/unitconv/target/debug/build/fltk-sys-c2de63b8459b5e6d/out/build/Release 
-L native=/Users/ionizing/github/unitconv/target/debug/build/fltk-sys-c2de63b8459b5e6d/out/lib 
-L native=/Users/ionizing/github/unitconv/target/debug/build/fltk-sys-c2de63b8459b5e6d/out/lib64 
-L native=/Users/ionizing/github/unitconv/target/debug/build/fltk-sys-c2de63b8459b5e6d/out/lib/Release 
-L native=/Users/ionizing/github/unitconv/target/debug/build/fltk-sys-c2de63b8459b5e6d/out/lib64/Release 
-l static=cfltk 
-l static=fltk 
-l static=fltk_images 
-l static=fltk_png 
-l static=fltk_jpeg 
-l static=fltk_z 
-l static=fltk_gl 
-l framework=OpenGL 
-l framework=Carbon 
-l framework=Cocoa 
-l framework=ApplicationServices`
```

## To Reproduce
```
$ cargo new some_binary
$ # Adding 'fltk = { version="1.1", features=["fltk-bundled", "enable-glwindow"] }' to the dependencies part of 'Cargo.toml'
$ cargo build
```

## Expected behavior
Should compiled.

## Desktop info
 - OS: macOS 10.15
 - Version: FLTK installed via Homebrew

## Additional info
I checked the dir `target/debug/build/fltk-sys-c2de63b8459b5e6d/out/lib` but found no static lib like `libfltk_gl.a`. If I copy it from `/usr/local/opt/fltk/lib/libfltk_gl.a` to `target/debug/build/fltk-sys-c2de63b8459b5e6d/out/lib`, `cargo build` compiles.

## Build failures
Though I've installed FLTK via Homebrew, I still want to use downloaded FLTK static lib bundle directly. I guess the `libfltk_gl.a` ought to be added to `lib_x64-macos.tar.gz`. Or users on macOS platform will need to install FLTK manually and add the library path to `fltk-sys/build/link.rs` if he want to use `enable-glwindow`.

**Comment by Ionizing** [comment] 2021-09-11 17:27
I checked `https://github.com/fltk-rs/fltk-rs/releases/download/1.1.17/lib_x64-macos.tar.gz` again and `libfltk_gl.a` is not included.

Looking forward to you reply!

**Comment by MoAlyousef** [comment] 2021-09-11 17:56
Currently that's the intended behavior. The bundle itself is built from the CI without the enable-glwindow flag, so OpenGL support isn't there. The reason is that it's not safe to assume the presence of OpenGL headers/library on Windows nor Linux (requires mesa).

**Comment by MoAlyousef** [comment] 2021-09-11 20:23
I have enabled the enable-glwindow flag for bundles, so the next release should see the deployment of fltk_gl lib, other code will still need to enable the same flag to get fltk_gl linked to their apps.

**Comment by Ionizing** [comment] 2021-09-12 03:07
> You can try the system-fltk feature however fltk-rs targets FLTK 1.4, so FLTK installed via homebrew will be abi-incompatible. You'll have to build FLTK from source and install it to a system PATH.

Ok, I'd better disable "fltk-bundled" feature when I want to use `glwindow`.

> so the next release should see the deployment of fltk_gl lib

Thanks for the job! I'll try it immediately when the release is updated~

**Comment by MoAlyousef** [comment] 2021-09-14 21:15
This should be addressed in 1.1.18.

**Closed by MoAlyousef** 2021-09-14 21:15 UTC

**Comment by Ionizing** [comment] 2021-09-15 01:44
I tested it on macOS and windows, both worked splendidly! Thank you very much.

**Comment by MoAlyousef** [comment] 2021-09-15 11:48
Unfortunately I had to revert the windows bundle since windows is less tolerant of undefined symbols. I’ll see if this can be fixed eventually or not.
