### ISSUE TITLE
failed to compile fltk-sys v1.2.24

### ISSUE THREAD

**Issue by Assassintears** [fltk-rs/fltk-rs#1083] opened 2021-12-30 03:36 UTC
Hi, I followed the fltk book first example to build fltk, I add `fltk = {version = "^1.2"}` to `Cargo.toml` under the `[dependencies]` session, and run `cargo build` command in `x64 Native Tools Command Prompt for VS2022`， then I get the error that `error: failed to run custom build command for fltk-sys v1.2.24`, the complete   error list:

```
D:\project\Rust\fltkk\src>cargo build
    Updating crates.io index
   Compiling cc v1.0.72
   Compiling crossbeam-utils v0.8.5
   Compiling lazy_static v1.4.0
   Compiling cfg-if v1.0.0
   Compiling bitflags v1.3.2
   Compiling paste v1.0.6
   Compiling cmake v0.1.46
   Compiling fltk-sys v1.2.24
   Compiling crossbeam-channel v0.5.1
error: failed to run custom build command for `fltk-sys v1.2.24`

Caused by:
  process didn't exit successfully: `D:\project\Rust\fltkk\target\debug\build\fltk-sys-bd79e32e6296c2ef\build-script-main` (exit code: 101)
  --- stdout
  cargo:rerun-if-changed=build/android.rs
  cargo:rerun-if-changed=build/bundled.rs
  cargo:rerun-if-changed=build/link.rs
  cargo:rerun-if-changed=build/main.rs
  cargo:rerun-if-changed=build/source.rs
  cargo:rerun-if-changed=build/utils.rs
  cargo:rerun-if-env-changed=CC
  cargo:rerun-if-env-changed=CXX
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-changed=cfltk/CMakeLists.txt
  cargo:rerun-if-changed=cfltk/include/cfl.h
  cargo:rerun-if-changed=cfltk/include/cfl_widget.h
  cargo:rerun-if-changed=cfltk/include/cfl_group.h
  cargo:rerun-if-changed=cfltk/include/cfl_input.h
  cargo:rerun-if-changed=cfltk/include/cfl_window.h
  cargo:rerun-if-changed=cfltk/include/cfl_button.h
  cargo:rerun-if-changed=cfltk/include/cfl_box.h
  cargo:rerun-if-changed=cfltk/include/cfl_menu.h
  cargo:rerun-if-changed=cfltk/include/cfl_dialog.h
  cargo:rerun-if-changed=cfltk/include/cfl_valuator.h
  cargo:rerun-if-changed=cfltk/include/cfl_browser.h
  cargo:rerun-if-changed=cfltk/include/cfl_misc.h
  cargo:rerun-if-changed=cfltk/include/cfl_text.h
  cargo:rerun-if-changed=cfltk/include/cfl_image.h
  cargo:rerun-if-changed=cfltk/include/cfl_draw.h
  cargo:rerun-if-changed=cfltk/include/cfl_table.h
  cargo:rerun-if-changed=cfltk/include/cfl_surface.h
  cargo:rerun-if-changed=cfltk/include/cfl_printer.h
  cargo:rerun-if-changed=cfltk/include/cfl_utils.h
  cargo:rerun-if-changed=cfltk/include/cfl_macros.h
  cargo:rerun-if-changed=cfltk/include/cfl_lock.h
  cargo:rerun-if-changed=cfltk/src/cfl_lock.cpp
  cargo:rerun-if-changed=cfltk/src/cfl_new.cpp
  cargo:rerun-if-changed=cfltk/src/cfl.cpp
  cargo:rerun-if-changed=cfltk/src/cfl_widget.cpp
  cargo:rerun-if-changed=cfltk/src/cfl_group.cpp
  cargo:rerun-if-changed=cfltk/src/cfl_window.cpp
  cargo:rerun-if-changed=cfltk/src/cfl_button.cpp
  cargo:rerun-if-changed=cfltk/src/cfl_box.cpp
  cargo:rerun-if-changed=cfltk/src/cfl_menu.cpp
  cargo:rerun-if-changed=cfltk/src/cfl_dialog.cpp
  cargo:rerun-if-changed=cfltk/src/cfl_valuator.cpp
  cargo:rerun-if-changed=cfltk/src/cfl_browser.cpp
  cargo:rerun-if-changed=cfltk/src/cfl_misc.cpp
  cargo:rerun-if-changed=cfltk/src/cfl_text.cpp
  cargo:rerun-if-changed=cfltk/src/cfl_image.cpp
  cargo:rerun-if-changed=cfltk/src/cfl_input.cpp
  cargo:rerun-if-changed=cfltk/src/cfl_draw.cpp
  cargo:rerun-if-changed=cfltk/src/cfl_table.cpp
  cargo:rerun-if-changed=cfltk/src/cfl_tree.cpp
  cargo:rerun-if-changed=cfltk/src/cfl_surface.cpp
  cargo:rerun-if-changed=cfltk/src/cfl_printer.cpp
  cargo:rerun-if-changed=cfltk/src/cfl_font.cpp
  cargo:rerun-if-changed=cfltk/src/cfl_utils.cpp
  cargo:rerun-if-changed=cfltk/src/cfl_nswindow.m
  cargo:rerun-if-changed=cfltk/FL_FLex/FL_Flex.H
  cargo:rerun-if-changed=cfltk/FL_FLex/FL_Flex.cpp
  cargo:rerun-if-changed=cfltk/src/cfl_vec.hpp
  CMAKE_TOOLCHAIN_FILE_x86_64-pc-windows-msvc = None
  CMAKE_TOOLCHAIN_FILE_x86_64_pc_windows_msvc = None
  HOST_CMAKE_TOOLCHAIN_FILE = None
  CMAKE_TOOLCHAIN_FILE = None
  CMAKE_GENERATOR_x86_64-pc-windows-msvc = None
  CMAKE_GENERATOR_x86_64_pc_windows_msvc = None
  HOST_CMAKE_GENERATOR = None
  CMAKE_GENERATOR = None
  CMAKE_PREFIX_PATH_x86_64-pc-windows-msvc = None
  CMAKE_PREFIX_PATH_x86_64_pc_windows_msvc = None
  HOST_CMAKE_PREFIX_PATH = None
  CMAKE_PREFIX_PATH = None
  CMAKE_x86_64-pc-windows-msvc = None
  CMAKE_x86_64_pc_windows_msvc = None
  HOST_CMAKE = None
  CMAKE = None

  --- stderr
  fatal: not a git repository (or any of the parent directories): .git
  error: patch failed: src/CMakeLists.txt:303
  error: src/CMakeLists.txt: patch does not apply
  error: patch failed: src/Fl_win32.cxx:603
  error: src/Fl_win32.cxx: patch does not apply
  error: patch failed: src/drivers/Android/Fl_Android_System_Driver.H:25
  error: src/drivers/Android/Fl_Android_System_Driver.H: patch does not apply
  thread 'main' panicked at 'Visual studio version detected but this crate doesn't know how to generate cmake files for it, can the `cmake` crate be updated?', D:\rust\cargo\registry\src\github.com-1ecc6299db9ec823\cmake-0.1.46\src\lib.rs:872:22
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

## and Tool chain is MSVC

please help me how to resolve this problem, thank you very much.

**Comment by MoAlyousef** [comment] 2021-12-30 08:59
Hi

It's a duplicate of this issue:
https://github.com/fltk-rs/fltk-rs/issues/1058

The cmake crate doesn't support your visual studio version as a generator, so you can use [ninja](https://github.com/ninja-build/ninja/releases) instead. Add ninja to your PATH, and in your project, use:
```toml
[dependencies]
fltk = { version = "1.2.24", features = ["use-ninja"] }
```

You can also try the fltk-bundled feature, it should also work with windows 11:
```toml
[dependencies]
fltk = { version = "1.2.24", features = ["fltk-bundled"] }
```

**Closed** 2021-12-30 10:21 UTC
Labels: duplicate

**Comment by Assassintears** [comment] 2021-12-31 05:54
Hi, I add the feature `use-ninja`， it still cannot build correctly. And I uninstall the vs2022 and reinstall vs2019, then I rebuild it and it tells me that  `Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)`

**Comment by MoAlyousef** [comment] 2021-12-31 12:11
Honestly it would've been easier just to try to fix your ninja install (less than 1 mb executable), than uninstalling and reinstalling a different toolchain probably breaking other things in the process. Or just trying fltk-bundled as suggested.
